
version: 2.1.5
server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001
# Database settings.
database:
  # the name of the JDBC driver, mysql in our case
  driverClass: com.mysql.jdbc.Driver
  # the username
  user: root
  # the password
  password: 0243
  # the JDBC URL; the database is called DWGettingStarted
  url: jdbc:mysql://localhost:3306/csshop